language: java
sudo: required
install:
   - sudo apt-get install --yes doxygen graphviz
script: 
   - jdk_switcher use oraclejdk8
   - mvn test
   - doxygen Doxyfile
   - mvn javadoc:javadoc
jdk: oraclejdk8